public class Nestedtry{
    public static void main(String[] args){
    try{
         try{
              System.out.println("going to divide");
              int a = 25/0;
         }
         catch(Exception e)
         {
            System.out.println("An Exception occured for first tryblock");
         }
         try
         { 
            int b = 26/0;
         }
         catch(Exception e)
         {
            System.out.println("Second try block Exception occured");
         }
         System.out.println("other catch");
   }
   catch(Exception e){
   System.out.println("End of the code");
   }
}
}
